// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzytTkmnYGFVYo3jfnfqET876RcFA-p_g',
    appId: '1:727050544736:web:5e51eed621c39600d64505',
    messagingSenderId: '727050544736',
    projectId: 'flutterecommerce-53ecf',
    authDomain: 'flutterecommerce-53ecf.firebaseapp.com',
    storageBucket: 'flutterecommerce-53ecf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgoQjqkMq01iSD8cVo2Ylmr_6c7afPe_4',
    appId: '1:727050544736:android:8b2bc96311a2e67fd64505',
    messagingSenderId: '727050544736',
    projectId: 'flutterecommerce-53ecf',
    storageBucket: 'flutterecommerce-53ecf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXDjFMrl9YwErcsozSHQwkbn2XtHLAiKQ',
    appId: '1:727050544736:ios:9e9f71d109e84c43d64505',
    messagingSenderId: '727050544736',
    projectId: 'flutterecommerce-53ecf',
    storageBucket: 'flutterecommerce-53ecf.firebasestorage.app',
    androidClientId: '727050544736-hmvh9org5ldb8mdqegkua1tcq1gqku19.apps.googleusercontent.com',
    iosClientId: '727050544736-k852d13deto0t85k5j0v8cfipas0gm24.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}